source 'http://rubygems.org'

ruby '2.2.3'

gem 'uuid'
gem 'base62'
gem 'colored'
gem 'bson'
gem 'bson_ext'
gem 'json'
gem 'net-ssh'
gem 'net-scp'
gem 'mongo', '~>1.12.0'
gem 'pg'
gem 'cassandra-driver'
gem 'daemons'
gem 'logger'
gem 'grape'
gem 'grape-swagger'
gem 'facter'
gem 'rufus-scheduler'
gem 'puma'
gem 'rubyipmi'
gem 'bzip2-ruby', '0.2.7', :git => 'https://github.com/chewi/bzip2-ruby.git'

group :test do
  gem 'rspec'
  gem 'rspec-mocks'
  gem 'rspec-expectations'
end
